import hashlib
import getpass

# Global session variable (simple in-memory session for CLI)
_current_user = None

def hash_password(password):
    """Hash a password using SHA-256."""
    return hashlib.sha256(password.encode()).hexdigest()

def get_current_user():
    """Get the currently logged-in user."""
    return _current_user

def set_current_user(user):
    """Set the current user session."""
    global _current_user
    _current_user = user

def logout():
    """Log out the current user."""
    global _current_user
    _current_user = None

def select_role():
    """Prompt user to select their role."""
    print("Select your role:")
    print("1. Patient (User)")
    print("2. Doctor")
    print("3. Administrator")
    print("4. I do not have a smartphone (Call-based access)")
    while True:
        try:
            choice = int(input("Enter your choice (1-4): "))
            if choice == 1:
                return "patient"
            elif choice == 2:
                return "doctor"
            elif choice == 3:
                return "admin"
            elif choice == 4:
                print("\nYou can access the health services using our free hotline number: 1234")
                print("You may also send a free SMS with your National ID to the same number.")
                return "call_based"
            else:
                print("Invalid choice. Please select 1-4.")
        except ValueError:
            print("Invalid input. Please enter a number.")

def register_user():
    """Register a new user."""
    print("\n--- User Registration ---")
    role = select_role()
    if role == "call_based":
        return None  # No registration needed for call-based

    username = input("Enter username: ").strip()
    if not username:
        raise ValueError("Username cannot be empty.")

    password = getpass.getpass("Enter password: ")
    if not password:
        raise ValueError("Password cannot be empty.")

    confirm_password = getpass.getpass("Confirm password: ")
    if password != confirm_password:
        raise ValueError("Passwords do not match.")

    hashed_password = hash_password(password)

    # Placeholder for database insertion
    # TODO: Insert user into database
    user = {
        "id": None,  # Would be generated by DB
        "username": username,
        "password_hash": hashed_password,
        "role": role
    }

    print(f"User {username} registered successfully as {role}.")
    return user

def login_user():
    """Log in an existing user."""
    print("\n--- User Login ---")
    role = select_role()
    if role == "call_based":
        return None  # No login needed for call-based

    username = input("Enter username: ").strip()
    password = getpass.getpass("Enter password: ")

    # Placeholder for database fetch
    # TODO: Fetch user from database by username and role
    # For now, simulate a user (in real app, this would be from DB)
    # Assuming user exists for demo
    stored_hash = hash_password(password)  # Simulate stored hash

    if username and password:  # Basic check
        user = {
            "id": 1,  # Simulated
            "username": username,
            "role": role
        }
        set_current_user(user)
        print(f"Logged in as {username} ({role}).")
        return user
    else:
        raise ValueError("Invalid username or password.")

# Error handling is built-in with try-except in calling code
